#!/bin/bash
# Deploy trust. platform to cloud (free tier)

echo "🚀 Starting free cloud deployment for trust. platform"
echo ""

echo "📋 Pre-deployment checklist:"
echo "□ Created Neon database account (https://neon.tech)"
echo "□ Created Railway account (https://railway.app)" 
echo "□ Have your GoDaddy domain ready"
echo "□ Have your Netlify site ready"
echo ""

echo "🎯 Deployment steps:"
echo ""
echo "1. DATABASE SETUP (Neon - Free):"
echo "   - Go to https://neon.tech"
echo "   - Sign up with GitHub"
echo "   - Create project: 'trust-platform'"
echo "   - Copy connection string"
echo ""

echo "2. BACKEND DEPLOYMENT (Railway - Free):"
echo "   - Go to https://railway.app"
echo "   - Connect GitHub repository"
echo "   - Deploy backend folder"
echo "   - Add environment variables:"
echo "     * DATABASE_URL: (from Neon)"
echo "     * JWT_SECRET: trust_platform_super_secret_key_2024"
echo "     * ALLOWED_ORIGINS: your-domain.com"
echo ""

echo "3. DATABASE INITIALIZATION:"
echo "   - Run schema against Neon database"
echo "   - Add demo shops and products"
echo ""

echo "4. FRONTEND UPDATE (Netlify):"
echo "   - Update VITE_API_URL to Railway backend URL"
echo "   - Redeploy frontend"
echo ""

echo "✅ Result: Worldwide access to trust. platform"
echo "💰 Cost: $0/month (free tiers)"
echo ""

read -p "Press Enter to continue with detailed setup instructions..."

echo ""
echo "🔧 DETAILED SETUP:"
echo ""
echo "=== NEON DATABASE SETUP ==="
echo "1. Visit: https://neon.tech"
echo "2. Click 'Sign up' → Continue with GitHub"
echo "3. Create new project: 'trust-platform'"
echo "4. Select region closest to your users"
echo "5. Copy the connection string (starts with 'postgresql://')"
echo ""

echo "=== RAILWAY BACKEND DEPLOYMENT ==="
echo "1. Visit: https://railway.app"
echo "2. Click 'Start a New Project' → 'Deploy from GitHub repo'"
echo "3. Connect your GitHub account if needed"
echo "4. Select your trust repository"
echo "5. Choose 'backend' as the root directory"
echo "6. Add these environment variables:"
echo "   DATABASE_URL: (paste your Neon connection string)"
echo "   JWT_SECRET: trust_platform_super_secret_key_2024"
echo "   NODE_ENV: production"
echo "7. Deploy!"
echo ""

echo "=== UPDATE FRONTEND ==="
echo "1. Copy your Railway app URL (ends with .railway.app)"
echo "2. In Netlify dashboard → Site settings → Environment variables"
echo "3. Add: VITE_API_URL = https://your-app.railway.app"
echo "4. Trigger new deploy"
echo ""

echo "🎉 Your trust. platform will be live worldwide!"
echo "📱 Access from any device, any network"
echo "💰 Completely free with generous limits"
